### ISSUE TITLE
Version mismatch between documentation and actual version

### ISSUE THREAD

**Issue by ChameleonTartu** [trifonnt/ext-lib-amazon-mws-orders#1]
`<version>1.0.0</version>` should be `<version>2017.12.04-17_43-5a26e23</version>`

**Comment by trifonnt** [comment]
@ChameleonTartu can you please specify which file need to be changed?
pom.xml ?

**Comment by ChameleonTartu** [comment]
In documentation you have example of dependency usage for Maven:

	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

 	<dependency>
	    <groupId>com.github.trifonnt</groupId>
	    <artifactId>ext-lib-amazon-mws-orders</artifactId>
	    <version>1.0.0</version>
	</dependency>

It should be like this instead:

	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

 	<dependency>
	    <groupId>com.github.trifonnt</groupId>
	    <artifactId>ext-lib-amazon-mws-orders</artifactId>
	    <version>2017.12.04-17_43-5a26e23</version>
	</dependency>

Based on the `Jitpack` builds.

**Comment by trifonnt** [comment]
@ChameleonTartu Thank you! I have updated documentation and this should be fixed now.
